alias gst='git status'
alias gc='git commit'
alias gco='git checkout'
alias gl='git pull'
alias glg='git log'
alias gb='git branch'
alias gmd='git merge-diff'
alias ..='cd ..'
alias ...='cd ../..'
alias dev='cd /cygdrive/d/dev/'
alias vim='vim -b'
alias vagssh='vagrant ssh -c "sudo bash"'
alias vagup="vagrant up"
alias gmd="git merge-diff"
alias gmdm="git merge-diff master"
alias lsa="ls -lart"
alias grh="git reset --hard"
alias gpo='git push origin'
alias gcb='git rev-parse --abbrev-ref HEAD'
alias gmdmc='gmdm (gcb)'
